stages:
  - build
  - deploy


build:
  stage: build
  image: node
  script:
     - apt update
     - npm install -g @angular/cli
     - npm install
     - ng build --prod
     - echo "BUILD SUCCESSFUL"
  artifacts:
    paths:
      - dist/
    only:
    - master

deploy:
  stage: deploy
  dependencies:
     - build
  before_script: 
      - mkdir -p ~/.ssh     
      - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
      - chmod 600 ~/.ssh/id_rsa     
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config' 
       
script:
      - scp -r dist/* ubuntu@$DEPLOY_SERVER:/home/ubuntu/foldername 
  environment:
    name: production
  only:
    - master